### ISSUE TITLE
Cordova android build fails

### ISSUE THREAD

**Issue by cosmocoder** [cakuki/cordova-plugin-viewport#3]
My cordova android build process started failing recently with the inclusion of this plugin, with the error message "unexpected token var". After debugging I finally pinpointed the source of this error to be this - https://github.com/cakuki/cordova-plugin-viewport/blob/8ec5174179d3cddb929a8ce9a08891ce72a957f4/set-viewport.js#L25

The comma at the end of line 25 needs to be turned to a semi-colon. I made the change manually in my downloaded copy of the plugin and the android build process works now. Although it is pretty strange that this error showed up for me only after upgrading to version 1.0.2, because I now see that this comma issue was also present in the previous version.

Hope you will fix the issue soon. This plugin saved me a lot of trouble with android viewport management 🙂

**Comment by cakuki** [comment]
Thank you very much for reporting! I fixed the issue and released `1.0.3`.
